// SML flashcard deck — built from Tübingen SML course (summer 2026)
// Each card: topic, term, def (short, used for matching/quiz), detail (optional longer note)
const DECK = [
  // ── Bayes decision theory ─────────────────────────────────────
  { topic: "Bayes & Decision Theory", term: "Bayes classifier (0-1 loss)",
    def: "Predict the class with highest posterior: argmax_y P(y|x)",
    detail: "For binary labels: f°(x) = 1 iff η(x) = P(Y=1|X=x) ≥ 1/2." },
  { topic: "Bayes & Decision Theory", term: "Bayes-optimal predictor (squared loss)",
    def: "f*(x) = E[Y | X = x], the conditional expectation",
    detail: "Its risk is the irreducible noise floor: R(f*) = E[Var(Y|X)]." },
  { topic: "Bayes & Decision Theory", term: "Bayes risk",
    def: "The lowest achievable risk of any predictor, R* = R(f*)",
    detail: "Under squared loss R* = E[Var(Y|X)] — irreducible noise." },
  { topic: "Bayes & Decision Theory", term: "ML vs. Bayes classifier",
    def: "ML ignores the class prior; Bayes weights class-conditionals by prior π(y)",
    detail: "They agree exactly when the prior is uniform." },
  { topic: "Bayes & Decision Theory", term: "Cost-sensitive classification",
    def: "Asymmetric losses shift the decision threshold on η(x) away from 1/2",
    detail: "Minimize conditional risk: predict 1 iff η(x)·cost(FN) ≥ (1−η(x))·cost(FP)." },
  { topic: "Bayes & Decision Theory", term: "Conditional risk",
    def: "Expected loss of a decision given x; the Bayes rule minimizes it pointwise",
    detail: "R(ŷ|x) = Σ_y L(y, ŷ) P(y|x)." },

  // ── Evaluation metrics ────────────────────────────────────────
  { topic: "Evaluation Metrics", term: "Confusion matrix",
    def: "2×2 table of TP, FP, FN, TN counts",
    detail: "Basis for accuracy, TPR, FPR, precision, recall." },
  { topic: "Evaluation Metrics", term: "Accuracy under class imbalance",
    def: "Misleading: 'approve everything' gets 95% accuracy at 5% positives",
    detail: "Use precision/recall or AUC instead when classes are imbalanced." },
  { topic: "Evaluation Metrics", term: "TPR (recall)",
    def: "TP / (TP + FN) — fraction of actual positives found",
    detail: "Also called sensitivity or hit rate." },
  { topic: "Evaluation Metrics", term: "FPR",
    def: "FP / (FP + TN) — fraction of negatives falsely flagged",
    detail: "x-axis of the ROC curve." },
  { topic: "Evaluation Metrics", term: "Precision",
    def: "TP / (TP + FP) — fraction of flagged items that are truly positive",
    detail: "Sensitive to class imbalance, unlike TPR/FPR." },
  { topic: "Evaluation Metrics", term: "ROC curve",
    def: "TPR plotted against FPR while sweeping the decision threshold",
    detail: "The diagonal is random guessing." },
  { topic: "Evaluation Metrics", term: "AUC",
    def: "P(random positive is scored above random negative)",
    detail: "Insensitive to class imbalance, but hides false-alarm volume (TN sits in the FPR denominator)." },
  { topic: "Evaluation Metrics", term: "Precision-Recall curve",
    def: "Invariant to TN count; exposes false alarms under heavy imbalance",
    detail: "Random baseline equals the positive prevalence, not 0.5." },

  // ── Learning theory ───────────────────────────────────────────
  { topic: "Learning Theory", term: "Consistency",
    def: "The risk converges to the Bayes risk: R(f_n) → R*",
    detail: "Convergence of risk, not pointwise convergence of the function." },
  { topic: "Learning Theory", term: "Universal consistency (k-NN)",
    def: "k-NN is universally consistent if k(n) → ∞ and k(n)/n → 0",
    detail: "Consistent for every data distribution." },
  { topic: "Learning Theory", term: "VC dimension",
    def: "Size of the largest set of points the class can shatter",
    detail: "Shatter = realize all 2^n labelings. Intervals on ℝ: VC = 2; union of ≤2 intervals: VC = 4." },
  { topic: "Learning Theory", term: "Shattering",
    def: "A class shatters n points if it realizes all 2^n possible labelings",
    detail: "Used to define VC dimension." },
  { topic: "Learning Theory", term: "Growth function",
    def: "N(F, n): maximum number of distinct labelings of n points by class F",
    detail: "Intervals on ℝ: N(n) = 1 + n + n(n−1)/2." },
  { topic: "Learning Theory", term: "Sauer–Shelah lemma",
    def: "VC dim d ⇒ growth function ≤ (en/d)^d — polynomial, not 2^n",
    detail: "N(F,n) ≤ Σ_{i≤d} C(n,i) ≤ (en/d)^d = O(n^d) for n ≥ d." },
  { topic: "Learning Theory", term: "Generalization bound (VC)",
    def: "Excess risk ≈ √( (d·log(n/d) + log(1/δ)) / n )",
    detail: "Holds with probability 1−δ; d = VC dimension." },
  { topic: "Learning Theory", term: "No Free Lunch theorem",
    def: "Averaged over all distributions, no learner beats any other",
    detail: "Escape it by assuming structure (priors, smoothness) about the world." },

  // ── Concentration inequalities ────────────────────────────────
  { topic: "Concentration Inequalities", term: "Markov inequality",
    def: "P(Z ≥ a) ≤ E[Z] / a for nonnegative Z",
    detail: "The weakest bound; needs only the mean." },
  { topic: "Concentration Inequalities", term: "Chebyshev inequality",
    def: "P(|Y − E[Y]| ≥ t) ≤ Var(Y) / t²",
    detail: "Derived by applying Markov to (Y − E[Y])²." },
  { topic: "Concentration Inequalities", term: "Hoeffding inequality",
    def: "Exponential tail bound for sums of bounded i.i.d. variables",
    detail: "Gives sample complexity n = Θ(1/ε²) for estimating a mean to accuracy ε." },
  { topic: "Concentration Inequalities", term: "Union bound",
    def: "P(A₁ ∪ … ∪ A_m) ≤ Σ P(Aᵢ)",
    detail: "Validate m classifiers simultaneously by allocating δ/m failure probability each." },
  { topic: "Concentration Inequalities", term: "Sample complexity (mean estimation)",
    def: "n = Θ(1/ε²) samples to estimate a mean to accuracy ε",
    detail: "Follows from Hoeffding's inequality." },

  // ── Perceptron ────────────────────────────────────────────────
  { topic: "Perceptron", term: "Perceptron update rule",
    def: "On a mistake (yᵢ⟨w, xᵢ⟩ ≤ 0): w ← w + yᵢxᵢ",
    detail: "Only updates on mistakes; converges if data is linearly separable." },
  { topic: "Perceptron", term: "Perceptron mistake bound",
    def: "M ≤ (R/ρ)² with ‖xᵢ‖ ≤ R and margin ρ",
    detail: "Independent of dimension and number of samples." },
  { topic: "Perceptron", term: "Margin perceptron mistake bound",
    def: "M ≤ (R² + 2ρ₀) / ρ² when updating whenever margin < ρ₀",
    detail: "Trades more updates for a guaranteed margin." },

  // ── Regression & regularization ───────────────────────────────
  { topic: "Regression & Regularization", term: "Normal equations",
    def: "XᵀX w = Xᵀ Y — characterizes the least-squares solution",
    detail: "Comes from orthogonality: residual ⊥ column space of X." },
  { topic: "Regression & Regularization", term: "OLS solution",
    def: "ŵ = (XᵀX)⁻¹ Xᵀ Y (when XᵀX is invertible)",
    detail: "Requires rank(X) = d, so needs n ≥ d." },
  { topic: "Regression & Regularization", term: "Ridge regression",
    def: "Minimize ‖Xw − Y‖² + λ‖w‖²; ŵ_λ = (XᵀX + λI)⁻¹XᵀY",
    detail: "Unique solution even when d > n, since XᵀX + λI is always invertible." },
  { topic: "Regression & Regularization", term: "LASSO / ℓ1 regularization",
    def: "ℓ1 penalty produces exactly-zero coefficients (sparsity)",
    detail: "Soft-thresholding; geometrically, the ℓ1 ball has corners on the axes." },
  { topic: "Regression & Regularization", term: "1-D regression coefficient",
    def: "w* = Cov(X, Y) / Var(X)",
    detail: "Interpretation caveat: association, not causation." },
  { topic: "Regression & Regularization", term: "Weighted least squares",
    def: "Reweight samples: solve XᵀWX w = XᵀWY",
    detail: "W is a diagonal matrix of per-sample weights." },
  { topic: "Regression & Regularization", term: "Gradient of ‖Bx − a‖²",
    def: "∇ = 2Bᵀ(Bx − a)",
    detail: "Standard matrix-calculus identity; also ∇(xᵀAx) = (A + Aᵀ)x." },

  // ── Ensembles & boosting ──────────────────────────────────────
  { topic: "Ensembles & Boosting", term: "Bagging",
    def: "Average models trained on bootstrap samples → variance reduction",
    detail: "Reduction depends on correlation ρ between the models." },
  { topic: "Ensembles & Boosting", term: "Bootstrap sample",
    def: "Draw n points from the training set with replacement",
    detail: "≈ 63% of unique points appear in each bootstrap sample." },
  { topic: "Ensembles & Boosting", term: "AdaBoost weight update",
    def: "Sample weights Dᵢ ∝ exp(−yᵢ f_{t−1}(xᵢ)) — upweight mistakes",
    detail: "Misclassified points get exponentially more weight each round." },
  { topic: "Ensembles & Boosting", term: "AdaBoost classifier weight",
    def: "w_t = ½ log((1 − ε_t) / ε_t)",
    detail: "Weak learners with lower weighted error ε_t get more say." },
  { topic: "Ensembles & Boosting", term: "AdaBoost training-error bound",
    def: "Training error ≤ exp(−2γ²T) if every round has ε_t ≤ ½ − γ",
    detail: "Via normalizer product: error ≤ Π_t 2√(ε_t(1−ε_t))." },
  { topic: "Ensembles & Boosting", term: "Gradient boosting",
    def: "Each base learner fits the pseudo-residuals (negative loss gradient)",
    detail: "For squared loss, pseudo-residuals are just the residuals y − ŷ." },
  { topic: "Ensembles & Boosting", term: "Decision stump",
    def: "A one-split decision tree; the classic AdaBoost weak learner",
    detail: "Thresholds a single feature." },

  // ── Algorithmic stability ─────────────────────────────────────
  { topic: "Algorithmic Stability", term: "Uniform stability",
    def: "Max loss change when one training point is replaced: sup |ℓ(A(S),z) − ℓ(A(Sⁱ),z)|",
    detail: "Small stability ⇒ small expected generalization gap." },
  { topic: "Algorithmic Stability", term: "Stability of the averaging rule",
    def: "Replacing one of n points changes the average by ≤ 2/n",
    detail: "So the averaging rule is uniformly stable with Δ = O(1/n)." },
  { topic: "Algorithmic Stability", term: "Stability ⇒ generalization",
    def: "Expected generalization gap is bounded by the uniform stability Δ",
    detail: "A key alternative route to generalization besides VC bounds." },
  { topic: "Algorithmic Stability", term: "SGD stability condition",
    def: "One-pass SGD on convex β-smooth losses is stable if η ≤ 2/β",
    detail: "Coupling argument: gradient step is a contraction with factor |1 − ηβ|." },

  // ── Overparameterization ──────────────────────────────────────
  { topic: "Overparameterization", term: "Double descent",
    def: "Test risk peaks at the interpolation threshold (p ≈ n), then falls again as p grows",
    detail: "Contradicts the classical U-shaped bias-variance picture." },
  { topic: "Overparameterization", term: "Interpolation threshold",
    def: "The model size p ≈ n where the model can just barely fit all training data",
    detail: "Where the double-descent risk spike occurs." },
  { topic: "Overparameterization", term: "Random Fourier features",
    def: "φ(x) = cos(ωᵀx + b), ω ~ N(0, I), b ~ Unif[0, 2π]",
    detail: "Random nonlinear features used to demonstrate double descent." },
  { topic: "Overparameterization", term: "Minimum-norm interpolator",
    def: "θ̂ = Xᵀ(XXᵀ)⁻¹y — the smallest-norm solution fitting all data",
    detail: "What gradient descent converges to in the overparameterized linear regime." },
  { topic: "Overparameterization", term: "Benign overfitting",
    def: "Interpolating noise yet achieving vanishing excess risk when d ≫ n",
    detail: "Whether overfitting is benign or harmful is decided by the covariance spectrum Σ (four regimes)." },
  { topic: "Overparameterization", term: "Near-orthogonality in high dimensions",
    def: "Random unit vectors are nearly orthogonal: P(|⟨u,v⟩| > t) ≤ 2e^(−c·d·t²)",
    detail: "Lets spiky interpolating components not hurt predictions elsewhere." },
  { topic: "Overparameterization", term: "Variance-preserving initialization",
    def: "Scale initial weights with Var ∝ 1/fan-in to keep activation variance constant",
    detail: "The Xavier/He initialization derivation." },

  // ── Fairness & explainability ─────────────────────────────────
  { topic: "Fairness & Explainability", term: "Equalized odds",
    def: "Equal TPR and equal FPR across protected groups",
    detail: "A single global threshold is generally insufficient when per-group ROC curves differ; may require randomization." },
  { topic: "Fairness & Explainability", term: "Fairness through unawareness (flaw)",
    def: "Dropping the protected attribute is not enough — proxies leak it",
    detail: "Correlated features (e.g. ZIP code) reconstruct the protected attribute." },
  { topic: "Fairness & Explainability", term: "Counterfactual explanation",
    def: "The minimal feature change that flips the model's decision",
    detail: "Basis for algorithmic recourse — actionable advice to affected users." },
  { topic: "Fairness & Explainability", term: "Algorithmic recourse",
    def: "Giving affected users an actionable path to change their outcome",
    detail: "Recourse actions should be actionable (not 'decrease your age')." },
  { topic: "Fairness & Explainability", term: "SHAP values",
    def: "Shapley-value-based feature attributions for a prediction",
    detail: "Caveat: they measure association within the model, not causation in the world." },
];

const TOPICS = [...new Set(DECK.map(c => c.topic))];
